In [45]:
import streamlit as st
import numpy as np
import pandas as pd
import pip
import plotly.express as px

APP_TITLE = "IRS INDIVIDUAL TAX FILING - 2020"
APP_SUB_TITLE = "STATEWISE/COUNTYWISE INCOME"

#Load IRS Data
pip.main(["install", "openpyxl"])
df = pd.read_csv('data/20incyall - 1024 - STProject.csv')

WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.

Requirement already satisfied: openpyxl in c:\users\13099\documents\gokula\uncc\dsba5122\irs_individual_tax_filing_2020\.venv\lib\site-packages (3.1.2)

Requirement already satisfied: et-xmlfile in c:\users\13099\documents\gokula\uncc\dsba5122\irs_individual_tax_filing_2020\.venv\lib\site-packages (from openpyxl) (1.1.0)

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3142 entries, 0 to 3141
Columns: 169 entries, State_code to Unemployment compensation (9) in Number of returns
dtypes: float64(4), int64(163), string(2)
memory usage: 4.1 MB

In [46]:
df.columns

Index(['State_code', 'State', 'County_code', 'County name', 'Latitude',
       'Longitude', 'Additional child tax credit in Amount',
       'Additional child tax credit in Number of returns',
       'Additional standard deduction in Amount',
       'Additional standard deduction in Number of returns',
       ...
       'Total tax credits (10) in Amount',
       'Total tax credits (10) in Number of returns',
       'Total tax liability (18) in Amount',
       'Total tax liability (18) in Number of returns',
       'Total tax payments in Amount',
       'Total tax payments in Number of returns', 'Total taxes paid in Amount',
       'Total taxes paid in Number of returns',
       'Unemployment compensation (9) in Amount',
       'Unemployment compensation (9) in Number of returns'],
      dtype='object', length=169)

In [49]:
df.State = df.State.astype('string')
df['County name'] = df['County name'].astype('string')

In [51]:
state = df["State"].unique()
print(state)
county = df["County name"].unique()
county

<StringArray>
['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL', 'GA', 'HI', 'ID',
 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO',
 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA',
 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY']
Length: 51, dtype: string

<StringArray>
[    'Autauga County',     'Baldwin County',     'Barbour County',
        'Bibb County',      'Blount County',     'Bullock County',
      'Butler County',     'Calhoun County',    'Chambers County',
    'Cherokee County',
 ...
      'Goshen County', 'Hot Springs County',     'Laramie County',
     'Natrona County',    'Niobrara County',    'Sublette County',
  'Sweetwater County',       'Uinta County',    'Washakie County',
      'Weston County']
Length: 1877, dtype: string

In [7]:
state = ['Alabama', 'Alaska', 'Arizona', 'Arkansas']
state

['Alabama', 'Alaska', 'Arizona', 'Arkansas']

In [53]:
filtered_df = df[df["State"].isin(state)]

In [54]:
ranking_g= filtered_df.groupby(['State','County name'], as_index=False).aggregate({'Number of single returns':'sum','Number of joint returns':'sum','Number of head of household returns':'sum', 'Total income in Amount':'sum'})
ranking_g

,State,County name,Number of single returns,Number of joint returns,Number of head of household returns,Total income in Amount
0,AK,Aleutians East Borough,510,190,130,3.841700e+04
1,AK,Aleutians West Census Area,1060,510,260,1.384330e+05
2,AK,Anchorage Municipality,80520,48090,15920,1.212046e+07
3,AK,Bethel Census Area,3670,1820,1290,2.872210e+05
4,AK,Bristol Bay Borough,280,150,30,3.002600e+04
...,...,...,...,...,...,...
3137,WY,Sweetwater County,9070,8110,2320,1.384473e+06
3138,WY,Teton County,8940,4910,930,6.411849e+06
3139,WY,Uinta County,4040,4320,990,6.019840e+05
3140,WY,Washakie County,1700,1680,330,2.440610e+05
3141,WY,Weston County,1510,1480,260,1.987510e+05

In [64]:
state_agg= filtered_df.groupby(['State'], as_index=False).aggregate({'Number of single returns':'sum','Number of joint returns':'sum','Number of head of household returns':'sum', 'Total income in Amount':'sum'})
state_agg

,State,Number of single returns,Number of joint returns,Number of head of household returns,Total income in Amount
0,AK,189470,123560,37170,2.635872e+07
1,AL,1046440,764000,384580,1.383511e+08
2,AR,619500,494200,206210,8.374384e+07
3,AZ,1755060,1160660,478520,2.435813e+08
4,CA,10399090,6333020,2475370,1.794572e+09
5,CO,1554940,1036420,278960,2.531624e+08
6,CT,975540,612830,224320,1.915449e+08
7,DC,234090,57720,50130,4.003418e+07
8,DE,256440,169950,69720,3.685729e+07
9,FL,5809890,3504230,1620200,8.763009e+08
10,GA,2470940,1593210,866260,3.456922e+08
11,HI,371910,244110,72420,5.057895e+07
12,IA,766050,602950,154730,1.056608e+08
13,ID,400030,375060,82570,6.188266e+07
14,IL,3243510,2092230,833110,5.036684e+08
15,IN,1658770,1193510,410300,2.107481e+08
16,KS,679590,541280,152990,9.987826e+07
17,KY,999230,758630,268620,1.215822e+08
18,LA,1010340,616750,420190,1.208577e+08
19,MA,2005120,1179350,373820,3.758448e+08
20,MD,1618480,964310,443020,2.669170e+08
21,ME,371310,261750,65600,4.764967e+07
22,MI,2626540,1751350,555220,3.385214e+08
23,MN,1500360,1071120,269810,2.326707e+08
24,MO,1495800,1077760,363620,1.979608e+08
25,MS,620360,395720,283240,6.839428e+07
26,MT,283680,209080,47980,3.758420e+07
27,NC,2447800,1769500,730720,3.454757e+08
28,ND,190000,142070,35070,2.821709e+07
29,NE,464580,365730,101220,6.778014e+07
30,NH,387220,277510,61030,6.556302e+07
31,NJ,2396020,1572520,615850,4.359698e+08
32,NM,517060,308750,155590,5.670549e+07
33,NV,858220,477990,230050,1.183804e+08
34,NY,5537300,2906060,1443750,8.859054e+08
35,OH,2945930,1864530,704640,3.873537e+08
36,OK,829720,666410,241230,1.060477e+08
37,OR,1091340,748810,201330,1.538136e+08
38,PA,3408960,2253060,731270,4.875808e+08
39,RI,322150,168940,68700,4.175483e+07
40,SC,1205400,851030,382000,1.608467e+08
41,SD,218450,173130,43350,3.181212e+07
42,TN,1633120,1180380,451510,2.235382e+08
43,TX,6740620,4728810,2066260,1.011392e+09
44,UT,703590,633570,131750,1.191735e+08
45,VA,2111980,1518370,491970,3.576996e+08
46,VT,186330,121950,29280,2.365183e+07
47,WA,1971000,1433500,376680,3.711170e+08
48,WI,1561260,1119770,283360,2.115420e+08
49,WV,391750,312700,93300,4.408986e+07
50,WY,139750,114630,26390,2.563416e+07

In [63]:
single = ranking_g["Total income in Amount"].agg("sum")
single

12631642150.030502

In [73]:
ranking_g.info()
single

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187 entries, 0 to 186
Data columns (total 6 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   State                                187 non-null    object
 1   County name                          187 non-null    object
 2   Number of single returns             12 non-null     float64
 3   Number of joint returns              187 non-null    object
 4   Number of head of household returns  187 non-null    object
 5   Total income in Amount               187 non-null    object
dtypes: float64(1), object(5)
memory usage: 8.9+ KB

6690.0

In [26]:
ranking_g.head(10)

,State,County name,Number of single returns,Number of joint returns,Number of head of household returns,Total income in Amount
0,Alabama,Autauga County,11410,10130,4100,1570301.0
1,Alabama,Baldwin County,49740,46300,13310,7974265.0
2,Alabama,Barbour County,5490,2790,2270,427190.0
3,Alabama,Bibb County,4440,3170,1550,431382.0
4,Alabama,Blount County,10120,11400,2630,1312861.0
5,Alabama,Bullock County,2540,710,1390,147608.0
6,Alabama,Butler County,4150,2330,2210,370609.0
7,Alabama,Calhoun County,24490,17140,8930,2503623.0
8,Alabama,Chambers County,7710,3850,3590,620845.0
9,Alabama,Cherokee County,4440,4670,1450,515776.0

In [66]:
import folium
from streamlit_folium import st_folium
map = folium.Map(location=[38, -96.5], zoom_start=4, scrollWheelZoom=False, tiles='CartoDB positron')
choropleth = folium.Choropleth(
    geo_data='data/us-state-boundaries.geojson',
    data=state_agg,
    columns=('State', 'Total income in Amount'),
    key_on='feature.properties.stusab',
    line_opacity=0.8,
    highlight=True
)
choropleth.geojson.add_to(map)

for feature in choropleth.geojson.data['features']:
    state_name = feature['properties']['stusab']
    feature['properties']['totalincome'] = 'Total income: ' + '{:,}'.format(state_agg[state_name, 'Total income in Amount'][0]) if state_name in list(df_indexed.index) else ''
    

choropleth.geojson.add_child(
    folium.features.GeoJsonTooltip(['stusab'],labels=False)
)
map

KeyError: ('PR', 'Total income in Amount')

In [58]:

map = folium.Map(location=[38, -96.5], zoom_start=4, scrollWheelZoom=False, tiles='CartoDB positron')
    
choropleth = folium.Choropleth(
    geo_data='data/gz_2010_us_050_00_500k.json',
    data=state_agg,
    columns=( 'State_code','Total income in Amount'),
    key_on='feature.properties.STATE',
    line_opacity=0.8,
    highlight=True
)
choropleth.geojson.add_to(map)
# #df_indexed = ranking_g.set_index('State')
# for feature in choropleth.geojson.data['features']:
#     state_name = feature['properties']['name']
#     feature['properties']['Total_income'] = 'Total income: ' + '{:,}'.format(ranking_g.loc[state_name, 'Total income in Amount'][0]) if state_name in list(df_indexed.index) else ''

choropleth.geojson.add_child(
    folium.features.GeoJsonTooltip(['name'],labels=False)
)

map

AssertionError: The field name is not available in the data. Choose from: ('GEO_ID', 'STATE', 'COUNTY', 'NAME', 'LSAD', 'CENSUSAREA').

In [73]:
import altair as alt
freq_chart = alt.Chart(state_agg).mark_bar().transform_filter(
            alt.FieldGTEPredicate(field='Total income in Amount', gte= 10000)
            ).encode(
        y=alt.Y('State',sort=alt.EncodingSortField('Total income in Amount', op='min', order='descending')),
        x='Total income in Amount'
    )



freq_text = freq_chart.mark_text(
    align='left',
    baseline='middle',
    dx=3
).encode(
    text=alt.Text('Total income in Amount',format='.1f')
)
freq_chart + freq_text

alt.LayerChart(...)